### ISSUE TITLE
Separate current research projects from old ones

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/capra-public#10]
The public page has descriptions for some (seemingly) inactive projects. In the hopes of getting undergrad researchers an accurate picture of the research projects that are currently active we can have two research sections, one for the "active" projects and one for the "inactive/finished" ones.

**Comment by sampsyo** [comment]
Yes! One thing I was also thinking of that would help with this would be to group projects by themes. For example, a soon-to-be-added Gator project description would go in the same "graphics programming" theme as Braid, although the latter is inactive, so it would serve the same purpose of having a more accurate current view of what we're up to.

**Comment by rachitnigam** [comment]
I like it. Do you have a draft of these themes? If you give me the themes, I'll bug the PhD students to submit short write-ups for their research.

**Comment by rachitnigam** [comment]
Maybe we can take inspiration from: https://github.com/plasma-umass/memory-landscape

**Comment by sampsyo** [comment]
Yeah; this is roughly what I had in mind:

- Graphics programming: Braid, Gator
- Accelerator generation: Dahlia, FuTIL
- Search-based compilers: Diospyros [standalone]
- New reconfigurable architecture: Trillium [probably don't have anything public to post yet]
- Vision/system co-design: vision mode, EVA2, DeepJPEG [archived]
- Intelligent systems & NLU: Opal [standalone] [archived]
